const GRUPOS_MUSCULARES = {
  pernas: "Pernas",
  gluteos: "Glúteos",
  peitoral: "Peitoral",
  bicepsAntebraco: "Bíceps/Antebraço",
  dorsais: "Dorsais (Costas)",
  deltoides: "Deltóides (Ombros)",
  triceps: "Tríceps",
  abdominais: "Abdominais"
};

const EXERCICIOS_LISTA = {
  pernas: [
    "AGACHAMENTO", "AFUNDO A FRENTE", "AGACHAMENTO SUMO", "STIFF", "AGACHAMENTO NA PAREDE", "LEG PRESS 90°", "MÁQUINA HACK", "LEG PRESS HORIZONTAL", "LEG PRESS 45", "EXTENSÃO UNILAT, SIMULT", "ADUÇÃO MÁQUINA", "ADUÇÃO CANELEIRA", "FLEXÃO QUADRIL COM CANELEIRA", "PANTURRILHA SENTADX", "PANTURRILHA LEG. HORIZONTAL", "PANTURRILHA LEG. 45"
  ],
  gluteos: [
    "AFUNDO A FRENTE", "FLEXÃO (DEITADX/SENTADX) GLUTEOS", "MAQUINA ABDUÇÃO", "ABDUÇÃO CANELEIRA", "EXTENSÃO QUADRIL (CROSS-OVER)", "GLUTEO 4 APOIOS PERNAS (FLEX/EXT)", "ELEVAÇÃO PELVICA"
  ],
  peitoral: [
    "FLEXÃO DE SOLO", "SUPINO HORIZONTAL CONVERGENTE", "SUPINO INCLINADO", "MÁQUINA PEITORAL", "VOADOR", "CROSS-OVER", "CRUCIFIXO", "CRUCIFIXO INCLINADO", "SUP HORIZ C/HALTER (C/ROTIS/ROT.)", "SUP. INCLIN. CHALTER (C/ROTIS/ROTJ", "PULL OVER"
  ],
  bicepsAntebraco: [
    "ROSCA DIRETA (BARRA/HALTER)", "ROSCA SCOTT", "ROSCA CONCENTRADA", "ROSCA MARTELO", "ROSCA INVERSA", "ROSCA PUNHO"
  ],
  dorsais: [
    "PUXADA ALTA (FRENTE/COSTAS)", "REMADA BAIXA (SENTADX/CURVADX)", "REMADA UNILATERAL (SERROTE)", "BARRA FIXA (PRONADA/SUPINADA)", "PULLDOWN", "LEVANTAMENTO TERRA"
  ],
  deltoides: [
    "DESENVOLVIMENTO (HALTER/BARRA)", "ELEVAÇÃO LATERAL", "ELEVAÇÃO FRONTAL", "REMADA ALTA", "VOADOR INVERSO", "CRUCIFIXO INVERSO"
  ],
  triceps: [
    "TRÍCEPS TESTA", "TRÍCEPS FRANCÊS", "TRÍCEPS CORDA", "TRÍCEPS COICE", "MERGULHO (BANCO/PARALELA)", "EXTENSÃO TRÍCEPS POLIA"
  ],
  abdominais: [
    "PRANCHA (FRONTA/LATERAL)", "ABDOMINAL REMADOR", "ABDOMINAL BICICLETA", "ELEVAÇÃO DE PERNAS", "ROLO ABDOMINAL", "CRUNCH"
  ]
};

// Exportar as constantes para que possam ser importadas em outros arquivos JS
export { GRUPOS_MUSCULARES, EXERCICIOS_LISTA };

